### ISSUE TITLE
exe无法运行

### ISSUE THREAD

**Issue by SpectreLL** [johnwayne1995/choroid-membranes_CVI#1]
老哥您好，我是一名眼科医学书，发现了你上传的脉络膜exe程序，于是下载下来使用。但是我在win10 21H2 无法运行脉络膜exe程序，也没有demo里面出来界面，只生成了一个空白的excel文件，请问应该如何解决呢？或者是这个exe需要哪些运行环境呢？非常感谢！

**Comment by johnwayne1995** [comment]
需要将jpg格式的眼底图片和choroid_qtw.exe文件放在一个文件夹下，已更新README

**Comment by SpectreLL** [comment]
我还有一些问题想向您请教，请问是否能够加一下您的微信呢？我的微信号是13229022096




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "johnwayne1995/choroid-membranes_CVI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月28日(星期四) 下午2:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [johnwayne1995/choroid-membranes_CVI] exe无法运行 (Issue #1)





 
需要将jpg格式的眼底图片和choroid_qtw.exe文件放在一个文件夹下，已更新README
